### ISSUE TITLE
Fatal error: Uncaught Twig\Error\LoaderError: Unable to find template

### ISSUE THREAD

**Issue by obritoluis** [NielsdeBlaauw/query-monitor-twig-profile#43]
Whenever I use include (e.g. {% include 'template.twig' %}) it shows that error. Any ideas on how to solve that?

**Comment by NielsdeBlaauw** [comment]
Hi @obritoluis 

Does the error also occur when the plugin is deactivated? 

If it does, it's probably not related to query-monitor-twig-profile.

If the problem is only there in combination with QMTP, can you please send a minimal example of your directory structure and twig environment setup in which the error is reproducible?

Thanks!
